# Generated by Django 5.1.4 on 2024-12-09 02:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mychats",
            old_name="me",
            new_name="myself",
        ),
    ]
